module.exports = 
    Object.freeze({
        16: {"name": "bool", "align": "center"},
        17: {"name": "bytea", "align": "left"},
        18: {"name": "char", "align": "left"},
        20: {"name": "int8", "align": "right"},
        21: {"name": "int2", "align": "right"},
        23: {"name": "int4","align": "right"},
        24: {"name":"regproc","align": "left"},
        25: {"name":"text","align": "left"},
        26: {"name":"oid","align": "right"},
        27: {"name":"txid","align": "right"},
        28: {"name":"xid","align": "right"},
        29: {"name":"cid","align": "right"},
        114: {"name":"json","align": "left"},
        142: {"name":"xml","align": "left"},
        194: {"name":"pg_node_tree","align": "left"},
        210: {"name":"smgr","align": "left"},
        602: {"name":"path","align": "left"},
        604: {"name":"polygon","align": "left"},
        650: {"name":"cidr","align": "center"},
        700: {"name":"float4","align": "right"},
        701: {"name":"float8","align": "right"},
        702: {"name":"abstime","align": "left"},
        703: {"name":"reltime","align": "left"},
        704: {"name":"tinterval","align": "right"},
        718: {"name":"circle","align": "left"},
        774: {"name":"macaddr8","align": "center"},
        790: {"name":"money","align": "right"},
        829: {"name":"macaddr","align": "center"},
        869: {"name":"inet","align": "center"},
        1033: {"name":"aclitem","align": "left"},
        1042: {"name":"bpchar","align": "left"},
        1043: {"name":"varchar","align": "left"},
        1082: {"name":"date","align": "left"},
        1083: {"name":"time","align": "left"},
        1114: {"name":"timestamp","align": "left"},
        1184: {"name":"timestamptz","align": "left"},
        1186: {"name":"interval","align": "left"},
        1266: {"name":"timetz","align": "left"},
        1560: {"name":"bit","align": "center"},
        1562: {"name":"varbit","align": "left"},
        1700: {"name":"numeric","align": "right"},
        1790: {"name":"refcursor","align": "left"},
        2202: {"name":"regprocedure","align": "left"},
        2203: {"name":"regoper","align": "left"},
        2204: {"name":"regoperator","align": "left"},
        2205: {"name":"regclass","align": "right"},
        2206: {"name":"regtype","align": "right"},
        2950: {"name":"uuid","align": "center"},
        2970: {"name":"txid_snpashot","align": "center"},
        3220: {"name":"pg_lsn","align": "center"},
        3361: {"name":"pg_ndistinct","align": "left"},
        3402: {"name":"pg_dependencies","align": "left"},
        3614: {"name":"tsvector","align": "left"},
        3615: {"name":"tsquery","align": "left"},
        3642: {"name":"gtsvector","align": "left"},
        3734: {"name":"regconfig","align": "left"},
        3769: {"name":"regdictionary","align": "left"},
        3802: {"name":"jsonb","align": "left"},
        4089: {"name":"regnamespace","align": "right"},
        4096: {"name":"regrole","align": "right"}
    });